name: Build and Push Docker Image

on:
  push:
    branches:
      - main #default and stable branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout code
       uses: actions/checkout@v2

      -name: Login to Docker Hub
       uses: docker/login-action@v1
       with: 
       username: ${{secrets.DOCKERHUB_USERNAME}}
       password: ${{secrets.DOCKER_PASSWORD}}

     -name: Build and Push Docker Image
      run: |
        docker build -t muizdev/crmbackend:latest .
        docker push muizdev/crmbackend:latest
