name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Adjust this if your default branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/backend-image-name:latest .
          docker push your-dockerhub-username/backend-image-name:latestatest
